#!/usr/bin/env python3
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Read the size data generated by the bash script
data = pd.read_csv('cnvr_size_data.tsv', sep='\t')

# Extract data columns
sizes = data['Size']
del_counts = data['Del']
dup_counts = data['Dup']
both_counts = data['Both']

# Create stacked bar chart
fig, ax = plt.subplots(figsize=(10, 6))

# Set bar width
bar_width = 0.7

# Create x positions for bars
x_pos = np.arange(len(sizes))

# Create stacked bars
ax.bar(x_pos, both_counts, bar_width, color='blue', label='Both')
ax.bar(x_pos, del_counts, bar_width, bottom=both_counts, color='#FF0000', label='Del')  # Gold/yellow color
ax.bar(x_pos, dup_counts, bar_width, bottom=both_counts + del_counts, color='#2E8B57', label='Dup')  # Green color

# Add labels, title and legend
ax.set_xlabel('Size (Kb)', fontsize=12)
ax.set_ylabel('Number of CNVRs', fontsize=12)
ax.set_title('Distribution of CNVRs by Size and Type', fontsize=14)
ax.set_xticks(x_pos)
ax.set_xticklabels(sizes)

# Add grid lines for y-axis only
ax.yaxis.grid(True, linestyle='--', alpha=0.7)

# Add legend in top right corner
ax.legend(loc='upper right')

# Layout adjustment
plt.tight_layout()

# Save the figure
plt.savefig('cnvr_size_distribution.png', dpi=300)
print("Plot saved as 'cnvr_size_distribution.png'")

# Display the plot
plt.show()